"""default template

Revision ID: 061b28a70bb4
Revises: fe1fe0e4d5e9
Create Date: 2026-02-17 08:02:30.780327

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '061b28a70bb4'
down_revision = 'fe1fe0e4d5e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_redeemed', sa.Boolean(), nullable=False),
    sa.Column('redeemed_by_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['redeemed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_code'), 'voucher', ['code'], unique=True)
    op.create_table('promotioncode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'APPLIED', 'CANCELLED', name='promotioncodestatus'), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['promotionplan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotioncode_code'), 'promotioncode', ['code'], unique=True)
    op.drop_index(op.f('ix_otp_phone'), table_name='otp')
    op.drop_table('otp')
    op.alter_column('deal', 'outcome',
               existing_type=postgresql.ENUM('bought', 'not_bought', 'cancelled', name='dealoutcome'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('meeting', 'buyer_response',
               existing_type=postgresql.ENUM('yes', 'no', 'not_yet', name='meetingresponse'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('meeting', 'seller_response',
               existing_type=postgresql.ENUM('yes', 'no', 'not_yet', name='meetingresponse'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'seller_response',
               existing_type=sa.String(),
               type_=postgresql.ENUM('yes', 'no', 'not_yet', name='meetingresponse'),
               existing_nullable=True)
    op.alter_column('meeting', 'buyer_response',
               existing_type=sa.String(),
               type_=postgresql.ENUM('yes', 'no', 'not_yet', name='meetingresponse'),
               existing_nullable=True)
    op.alter_column('deal', 'outcome',
               existing_type=sa.String(),
               type_=postgresql.ENUM('bought', 'not_bought', 'cancelled', name='dealoutcome'),
               nullable=False)
    op.create_table('otp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_pkey'))
    )
    op.create_index(op.f('ix_otp_phone'), 'otp', ['phone'], unique=False)
    op.drop_index(op.f('ix_promotioncode_code'), table_name='promotioncode')
    op.drop_table('promotioncode')
    op.drop_index(op.f('ix_voucher_code'), table_name='voucher')
    op.drop_table('voucher')
    # ### end Alembic commands ###
