"""default template

Revision ID: 1166429523d3
Revises: 061b28a70bb4
Create Date: 2026-02-18 22:09:54.206099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1166429523d3'
down_revision = '061b28a70bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobiletransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_linked', sa.Boolean(), nullable=False),
    sa.Column('linked_promotion_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_promotion_id'], ['promotion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobiletransaction_phone'), 'mobiletransaction', ['phone'], unique=False)
    op.create_index(op.f('ix_mobiletransaction_reference'), 'mobiletransaction', ['reference'], unique=True)
    op.add_column('promotion', sa.Column('payment_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('promotion', sa.Column('amount', sa.Float(), nullable=True))
    op.execute("UPDATE promotion SET amount = 0.0 WHERE amount IS NULL")
    op.alter_column('promotion', 'amount', nullable=False)
    op.add_column('user', sa.Column('is_agent', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET is_agent = False WHERE is_agent IS NULL")
    op.alter_column('user', 'is_agent', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_agent')
    op.drop_column('promotion', 'amount')
    op.drop_column('promotion', 'payment_phone')
    op.drop_index(op.f('ix_mobiletransaction_reference'), table_name='mobiletransaction')
    op.drop_index(op.f('ix_mobiletransaction_phone'), table_name='mobiletransaction')
    op.drop_table('mobiletransaction')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
