"""default template

Revision ID: 2504bfbfb243
Revises: 9a2b3c4d5e6f
Create Date: 2026-02-13 16:40:03.363117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2504bfbfb243'
down_revision = '9a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user', sa.Column('sms_notifications', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sms_notifications')
    op.drop_column('user', 'email_notifications')
    # ### end Alembic commands ###
