"""default template

Revision ID: a62488cbd3c2
Revises: 3a9a31b736c9
Create Date: 2026-01-01 15:18:52.182751

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a62488cbd3c2'
down_revision = '3a9a31b736c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'images')
    # ### end Alembic commands ###
