"""default template

Revision ID: fe1fe0e4d5e9
Revises: b16cc5db8eaa
Create Date: 2026-02-16 16:18:35.839601

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe1fe0e4d5e9'
down_revision = 'b16cc5db8eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interaction', 'type',
               existing_type=postgresql.ENUM('call', 'whatsapp', name='interactiontype'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('listing', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USD'::character varying"))
    op.drop_constraint(op.f('uq_promotion_promotion_code'), 'promotion', type_='unique')
    op.drop_index(op.f('ix_promotion_promotion_code'), table_name='promotion')
    op.create_index(op.f('ix_promotion_promotion_code'), 'promotion', ['promotion_code'], unique=True)
    op.add_column('user', sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_verified')
    op.drop_index(op.f('ix_promotion_promotion_code'), table_name='promotion')
    op.create_index(op.f('ix_promotion_promotion_code'), 'promotion', ['promotion_code'], unique=False)
    op.create_unique_constraint(op.f('uq_promotion_promotion_code'), 'promotion', ['promotion_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('listing', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USD'::character varying"))
    op.alter_column('interaction', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('call', 'whatsapp', name='interactiontype'),
               nullable=False)
    # ### end Alembic commands ###
