"""default template

Revision ID: 8e906b4a5f98
Revises: f2e1d0c9b8a7
Create Date: 2026-04-13 22:55:28.620220

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8e906b4a5f98'
down_revision = 'f2e1d0c9b8a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_so', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_key'), 'site_content', ['key'], unique=True)
    op.create_index(op.f('ix_site_content_page_group'), 'site_content', ['page_group'], unique=False)
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_index(op.f('ix_category_name_en'), 'category', ['name_en'], unique=False)
    op.drop_index(op.f('ix_listing_title'), table_name='listing')
    op.create_index(op.f('ix_listing_title_en'), 'listing', ['title_en'], unique=False)
    op.drop_index(op.f('ix_subcategory_name'), table_name='subcategory')
    op.create_index(op.f('ix_subcategory_name_en'), 'subcategory', ['name_en'], unique=False)
    op.drop_index(op.f('ix_subsubcategory_name'), table_name='subsubcategory')
    op.create_index(op.f('ix_subsubcategory_name_en'), 'subsubcategory', ['name_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subsubcategory_name_en'), table_name='subsubcategory')
    op.create_index(op.f('ix_subsubcategory_name'), 'subsubcategory', ['name_en'], unique=False)
    op.drop_index(op.f('ix_subcategory_name_en'), table_name='subcategory')
    op.create_index(op.f('ix_subcategory_name'), 'subcategory', ['name_en'], unique=False)
    op.drop_index(op.f('ix_listing_title_en'), table_name='listing')
    op.create_index(op.f('ix_listing_title'), 'listing', ['title_en'], unique=False)
    op.drop_index(op.f('ix_category_name_en'), table_name='category')
    op.create_index(op.f('ix_category_name'), 'category', ['name_en'], unique=True)
    op.drop_index(op.f('ix_site_content_page_group'), table_name='site_content')
    op.drop_index(op.f('ix_site_content_key'), table_name='site_content')
    op.drop_table('site_content')
    # ### end Alembic commands ###
