"""add support ticket model

Revision ID: 9f8e7d6c5b4a
Revises: merge_heads_001
Create Date: 2026-05-10 22:23:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f8e7d6c5b4a'
down_revision = 'merge_heads_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supportticket',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_history', sa.JSON(), nullable=True),
        sa.Column('last_agent_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('admin_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supportticket')
    # ### end Alembic commands ###
