"""default template

Revision ID: d53d51871762
Revises: 59ee1dc2a297
Create Date: 2026-04-13 02:00:28.062197

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd53d51871762'
down_revision = '59ee1dc2a297'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('listing', sa.Column('admin_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'admin_notes')
    op.drop_column('listing', 'rejection_reason')
    # ### end Alembic commands ###
